Requesting Approval to merge "Main section" into "Master" branch
geekelo/a-personal-portfolio-site pull request #2
Opened 2023-04-29 21:24 UTC by geekelo

Dear Code Reviewer,

I hope this message finds you well. I am reaching out to request your assistance with reviewing my code. I would greatly appreciate it if you could take a look at the code and provide any feedback or suggestions for improvement.

Thank you in advance for your time and feedback. I look forward to hearing from you soon.

Best regards

2023-04-29 21:32 UTC, V-Blaze requested changes
Hi @geekelo  , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![dcentl8-9b96e129-9725-401b-ac34-2feb990202a0](https://user-images.githubusercontent.com/107632780/229646232-19bbafea-ca96-4b36-ad5d-1d64c00d667c.gif)

## Invalid Code Review Request

## You have submitted a project, that has a failed linter check, As required by Microverse, All your linter checks must pass before requesting for a review

## Also You did great adding a pull request summary, But following the best practice, A pull request summary should be a brief point and list of all the features you added to the current branch I'll greatly advise you edit your pull request description and add an eye-catching summary. :smile: :wave: :+1: 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-01 09:00 UTC, brainconnect93 requested changes
## STATUS: Changes Required :recycle:

### Hi @geekelo, 👋 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.tenor.com/isiLRnxz3zwAAAAM/cat-driving-serious.gif" width="500px" height="300px">

## Good Points 👍

- Descriptive Pull Request title and summary. ✔️
-  Create the project cards and well aligned✔️
- Create the About me section with the tech stack ✔️
- Descriptive and professional README file ✔️
- Good use of Github flow ✔️

### Changes Required

- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @brainconnect93 ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-01 09:00 UTC, brainconnect93 commented on index.html
> +	      <div class="metaCategories"><p>CANOPY</p></div>
- [ ] I would kindly suggest you make this part and other part that are of thesame type be inside of an `hx` tag i.e `h2-h6`.
I would preferably ask you to make use of an `h3` tag rather than the `p` tag you have there. As this will show that you have follow the project requirement as much as possible.

2023-05-01 09:00 UTC, brainconnect93 commented on index.html
> +          <h1>About Myself</h1>
- [ ] According to the requirement we are told to use an `hx` tag, which you have rightly used. But it is of the best practice to have only one `h1` tag in a webpage and you have used that when working with the header section. I would kindly suggest you make use of `h2-h6` tag here, preferably `h2` tag

2023-05-01 09:00 UTC, brainconnect93 commented on index.html
> +	</div>
- [ ] As stated in the requirement, I would kindly advice you make The technology categories ("Languages", "Frameworks" and "Skills") are in a `ul`, each of them in a `li`. this will show confidence in your ability to follow any given requirement.

2023-05-01 11:06 UTC, mckent05 approved these changes
Hi @geekelo, 

# STATUS: APPROVED ✔️ ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations and well done! 🎉 
![approved](https://user-images.githubusercontent.com/73607512/207264357-1b05ce6a-95f2-4d31-9c26-888c6ddfa124.gif)


## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👏 👏 
- Your project looks good, welldone 👍 👍 

## Optional suggestions
**OPTIONAL** - According to the project requirements, please make sure your mobile version is responsible for all screen sizes between `375px` and `768px`. This would ensure your website fits into all mobile screen and tabs.

Your project:
![vnxfb](https://user-images.githubusercontent.com/73607512/235443910-db5936e5-779f-41b0-90e7-b803c337b3b7.PNG)


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-01 11:06 UTC, mckent05 commented on index.html
> +	    </ul>
**OPTIONAL** - Good job following the advice of the previous reviewer, but to ensure your page is properly semantically correct, please put this `ul` and its children in the first `li` tag. Please fix this 🙏

2023-05-01 11:35 UTC, geekelo commented on index.html
> +	    </ul>
Thank you @mckent05

2023-05-01 11:35 UTC, merged